/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intaface;

/**
 *
 * @author KRcsa
 */
public class addComp extends javax.swing.JFrame {

    /**
     * Creates new form addComp
     */
    public addComp() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        compUnitMeasure = new javax.swing.JLabel();
        compTotalValue = new javax.swing.JLabel();
        compUnitMeasure_field = new javax.swing.JTextField();
        compUnitValue = new javax.swing.JLabel();
        compQuantity_field = new javax.swing.JTextField();
        compDate = new javax.swing.JLabel();
        compDate_field = new javax.swing.JTextField();
        compQuantity_PropCard_field = new javax.swing.JTextField();
        compRemarks = new javax.swing.JLabel();
        compRemarks_field = new javax.swing.JTextField();
        compAdd_button = new javax.swing.JButton();
        compClose_button = new javax.swing.JButton();
        compUnitValue_field = new javax.swing.JTextField();
        compTotalValue_field = new javax.swing.JTextField();
        compQuantity_PropCard = new javax.swing.JLabel();
        compQuantity = new javax.swing.JLabel();
        comp_specs = new javax.swing.JLabel();
        comp_specs_field = new javax.swing.JTextField();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(160, 160));
        setResizable(false);

        compUnitMeasure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compUnitMeasure.setText("Unit of Measure:");

        compTotalValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compTotalValue.setText("Total Value:    PHP");

        compUnitMeasure_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compUnitMeasure_fieldActionPerformed(evt);
            }
        });

        compUnitValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compUnitValue.setText("Unit Value:     PHP");

        compQuantity_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compQuantity_fieldActionPerformed(evt);
            }
        });

        compDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compDate.setText("Date Aquired:");

        compQuantity_PropCard_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compQuantity_PropCard_fieldActionPerformed(evt);
            }
        });

        compRemarks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compRemarks.setText("Remarks: ");

        compRemarks_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compRemarks_fieldActionPerformed(evt);
            }
        });

        compAdd_button.setText("ADD");
        compAdd_button.setPreferredSize(new java.awt.Dimension(90, 30));
        compAdd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compAdd_buttonActionPerformed(evt);
            }
        });

        compClose_button.setText("DONE");
        compClose_button.setPreferredSize(new java.awt.Dimension(90, 30));
        compClose_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compClose_buttonActionPerformed(evt);
            }
        });

        compTotalValue_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compTotalValue_fieldActionPerformed(evt);
            }
        });

        compQuantity_PropCard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compQuantity_PropCard.setText("Quantity per Property Card:");

        compQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compQuantity.setText("Quantity per Physical Count:");

        comp_specs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comp_specs.setText("Component(s)/SPECS");

        comp_specs_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_specs_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comp_specs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comp_specs_field))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compQuantity_PropCard)
                                    .addComponent(compQuantity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(compQuantity_PropCard_field, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(compQuantity_field)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(compUnitMeasure, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compDate, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(compUnitMeasure_field, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(compDate_field))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compTotalValue)
                                    .addComponent(compUnitValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compUnitValue_field)
                                    .addComponent(compTotalValue_field)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compRemarks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(compAdd_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(compClose_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(compRemarks_field))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp_specs)
                    .addComponent(comp_specs_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compUnitValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(compDate)
                        .addComponent(compDate_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(compUnitValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compUnitMeasure)
                    .addComponent(compUnitMeasure_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compTotalValue)
                    .addComponent(compTotalValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compQuantity_PropCard)
                    .addComponent(compQuantity_PropCard_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compRemarks)
                    .addComponent(compRemarks_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compQuantity)
                    .addComponent(compQuantity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compAdd_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compClose_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compUnitMeasure_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compUnitMeasure_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compUnitMeasure_fieldActionPerformed

    private void compTotalValue_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compTotalValue_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compTotalValue_fieldActionPerformed

    private void compAdd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compAdd_buttonActionPerformed

    }//GEN-LAST:event_compAdd_buttonActionPerformed

    private void compQuantity_PropCard_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compQuantity_PropCard_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compQuantity_PropCard_fieldActionPerformed

    private void compQuantity_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compQuantity_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compQuantity_fieldActionPerformed

    private void comp_specs_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_specs_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_specs_fieldActionPerformed

    private void compClose_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compClose_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_compClose_buttonActionPerformed

    private void compRemarks_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compRemarks_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compRemarks_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compAdd_button;
    private javax.swing.JButton compClose_button;
    private javax.swing.JLabel compDate;
    private javax.swing.JTextField compDate_field;
    private javax.swing.JLabel compQuantity;
    private javax.swing.JLabel compQuantity_PropCard;
    private javax.swing.JTextField compQuantity_PropCard_field;
    private javax.swing.JTextField compQuantity_field;
    private javax.swing.JLabel compRemarks;
    private javax.swing.JTextField compRemarks_field;
    private javax.swing.JLabel compTotalValue;
    private javax.swing.JTextField compTotalValue_field;
    private javax.swing.JLabel compUnitMeasure;
    private javax.swing.JTextField compUnitMeasure_field;
    private javax.swing.JLabel compUnitValue;
    private javax.swing.JTextField compUnitValue_field;
    private javax.swing.JLabel comp_specs;
    private javax.swing.JTextField comp_specs_field;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
