/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intaface;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author MAJADAS
 */
public class AddEquipmentForm extends javax.swing.JDialog {
private SAMPLE1 inventory;
    /**
     * Creates new form AddEquipmentForm
     */
    public AddEquipmentForm(intaface.SAMPLE1 parent, boolean modal) {
        super(parent, modal);
        inventory = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipment_des = new javax.swing.JLabel();
        equipmentName = new javax.swing.JLabel();
        equipmentName_field = new javax.swing.JTextField();
        comp_specs = new javax.swing.JLabel();
        comp_specs_button = new javax.swing.JButton();
        dateAcquired = new javax.swing.JLabel();
        dateAcquired_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        compArea_field = new javax.swing.JTextArea();
        equipPropNo = new javax.swing.JLabel();
        equipPropNo_field = new javax.swing.JTextField();
        equipUnitOfMeasure = new javax.swing.JLabel();
        equipUnitOfMeasure_field = new javax.swing.JTextField();
        equipUnitValue = new javax.swing.JLabel();
        equipUnitValue_field = new javax.swing.JTextField();
        equipQuantity = new javax.swing.JLabel();
        equipQuantity_field = new javax.swing.JTextField();
        equipTotalValue = new javax.swing.JLabel();
        equipTotalValue_field = new javax.swing.JTextField();
        remarks = new javax.swing.JLabel();
        remarks_field = new javax.swing.JTextField();
        formAddButton = new javax.swing.JButton();
        formCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD EQUIPMENT");

        equipment_des.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        equipment_des.setText("DESCRIPTION");

        equipmentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipmentName.setText("Equipment Name:");

        equipmentName_field.setPreferredSize(new java.awt.Dimension(90, 30));

        comp_specs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comp_specs.setText("Component(s)/SPECS:");

        comp_specs_button.setText("Add");
        comp_specs_button.setPreferredSize(new java.awt.Dimension(90, 30));
        comp_specs_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_specs_buttonActionPerformed(evt);
            }
        });

        dateAcquired.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateAcquired.setText("Date Acquired:");

        dateAcquired_field.setPreferredSize(new java.awt.Dimension(90, 30));

        compArea_field.setColumns(20);
        compArea_field.setRows(5);
        jScrollPane1.setViewportView(compArea_field);

        equipPropNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipPropNo.setText("Property Number: ");

        equipPropNo_field.setPreferredSize(new java.awt.Dimension(90, 30));

        equipUnitOfMeasure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipUnitOfMeasure.setText("Unit of Measure:");

        equipUnitOfMeasure_field.setPreferredSize(new java.awt.Dimension(90, 30));

        equipUnitValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipUnitValue.setText("Unit Value:   Php");

        equipUnitValue_field.setPreferredSize(new java.awt.Dimension(90, 30));

        equipQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipQuantity.setText("Quantity per Physical Count:");

        equipQuantity_field.setPreferredSize(new java.awt.Dimension(90, 30));

        equipTotalValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipTotalValue.setText("Total Value: Php");

        equipTotalValue_field.setEditable(false);
        equipTotalValue_field.setForeground(new java.awt.Color(204, 204, 204));
        equipTotalValue_field.setPreferredSize(new java.awt.Dimension(90, 30));

        remarks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remarks.setText("Remarks:");

        remarks_field.setPreferredSize(new java.awt.Dimension(90, 30));

        formAddButton.setText("ADD");
        formAddButton.setPreferredSize(new java.awt.Dimension(90, 30));

        formCancelButton.setText("CANCEL");
        formCancelButton.setPreferredSize(new java.awt.Dimension(90, 30));
        formCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comp_specs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comp_specs_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(dateAcquired)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateAcquired_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipmentName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipmentName_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(equipPropNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipPropNo_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipQuantity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipUnitOfMeasure)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipUnitOfMeasure_field, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipUnitValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipUnitValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipTotalValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipTotalValue_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(equipment_des)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remarks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remarks_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(formCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(formAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equipment_des)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipmentName)
                    .addComponent(equipmentName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp_specs)
                    .addComponent(comp_specs_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateAcquired)
                    .addComponent(dateAcquired_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipPropNo)
                    .addComponent(equipPropNo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipUnitOfMeasure)
                    .addComponent(equipUnitOfMeasure_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipUnitValue)
                    .addComponent(equipUnitValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipQuantity)
                    .addComponent(equipQuantity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipTotalValue)
                    .addComponent(equipTotalValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remarks)
                    .addComponent(remarks_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(545, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCancelButtonActionPerformed
        // TODO add your handling code here:
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }//GEN-LAST:event_formCancelButtonActionPerformed

    private void comp_specs_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_specs_buttonActionPerformed
        AddCompForm compForm = new AddCompForm(inventory, true);
        compForm.setVisible(true);
    }//GEN-LAST:event_comp_specs_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEquipmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEquipmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEquipmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEquipmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEquipmentForm dialog = new AddEquipmentForm(new intaface.SAMPLE1(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea compArea_field;
    private javax.swing.JLabel comp_specs;
    private javax.swing.JButton comp_specs_button;
    private javax.swing.JLabel dateAcquired;
    private javax.swing.JTextField dateAcquired_field;
    private javax.swing.JLabel equipPropNo;
    private javax.swing.JTextField equipPropNo_field;
    private javax.swing.JLabel equipQuantity;
    private javax.swing.JTextField equipQuantity_field;
    private javax.swing.JLabel equipTotalValue;
    private javax.swing.JTextField equipTotalValue_field;
    private javax.swing.JLabel equipUnitOfMeasure;
    private javax.swing.JTextField equipUnitOfMeasure_field;
    private javax.swing.JLabel equipUnitValue;
    private javax.swing.JTextField equipUnitValue_field;
    private javax.swing.JLabel equipmentName;
    private javax.swing.JTextField equipmentName_field;
    private javax.swing.JLabel equipment_des;
    private javax.swing.JButton formAddButton;
    private javax.swing.JButton formCancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextField remarks_field;
    // End of variables declaration//GEN-END:variables
}
